export const ADD_BUN_INGREDIENT = 'ADD_BUN_INGREDIENT';
export const ADD_MAIN_INGREDIENT = 'ADD_MAIN_INGREDIENT';
export const DELETE_MAIN_INGREDIENT = 'DELETE_MAIN_INGREDIENT';
export const SORT_INGREDIENTS = 'SORT_INGREDIENTS';
